### ISSUE TITLE
Internal error - Post the following stack trace here

### ISSUE THREAD

**Issue by TWT-MW** [sascha-egerer/phpstan-typo3#106]
Greetings everyone, 

PHPStan told me to post the following text:

### Env

- PHP 8.1
- typo3/cms-core: 11.5.18
- georgringer/news: 9.4.0
- saschaegerer/phpstan-typo3: 1.8.1
- ssch/typo3-rector: 1.0.2

### Code
```
<?php

namespace Vendor\MyExtension\ViewHelpers;

use GeorgRinger\News\Domain\Model\Dto\NewsDemand;
use GeorgRinger\News\Domain\Repository\NewsRepository;
use TYPO3\CMS\Core\Utility\GeneralUtility;
use TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper;
// @see https://github.com/georgringer/news/blob/main/Classes/Domain/Repository/NewsRepository.php

/**
 * NewsRecordsViewHelper
 */
class NewsRecordsViewHelper extends AbstractViewHelper
{
    public function initializeArguments(): void
    {
        $this->registerArgument('categorisUidList', 'string', 'Categories Uid List', true);
        $this->registerArgument('maxNumber', 'int', 'Max Numbers of News', true);
        $this->registerArgument('detailPage', 'string', 'News Detail Page', true);
    }

    public function render(): array
    {
        $newsRepository = GeneralUtility::makeInstance(NewsRepository::class);
        $newsDemand = GeneralUtility::makeInstance(NewsDemand::class);
        $newsDemand->setCategories(GeneralUtility::trimExplode(',', $this->arguments['categorisUidList'] ?? '', true));
        $newsDemand->setCategoryConjunction('or');
        $newsDemand->setOrder('tstamp');
        $newsDemand->setLimit($this->arguments['maxNumber']);

        $res['news'] = $newsRepository->findDemanded($newsDemand)->toArray();
        $res['settings']['detailPid'] = explode('uid=', (string) $this->arguments['detailPage'])[1];

        return $res;
    }
}

```

Note:
If I delete the line `$res['news'] = $newsRepository->findDemanded($newsDemand)->toArray();` it's working fine. The problem seems to be the part `->toArray()`.

### Error 
```
Internal error: Internal error: Repository class "Vendor\MyExtensionViewHelpers\NewsRecordsViewHelper" must implement "TYPO3\CMS\Extbase\Persistence\RepositoryInterface" in file                                                                 
/var/www/html/app/packages/my_extension/Classes/ViewHelpers/NewsRecordsViewHelper.php
```

### Stacktrace
```
#0 /var/www/html/app/vendor/saschaegerer/phpstan-typo3/src/Type/QueryResultToArrayDynamicReturnTypeExtension.php(60): SaschaEgerer\PhpstanTypo3\Type\QueryResultToArrayDynamicReturnTypeExtension->translateRepositoryNameToModelName('Vendor\\My...')
#1 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3488): SaschaEgerer\PhpstanTypo3\Type\QueryResultToArrayDynamicReturnTypeExtension->getTypeFromMethodCall(Object(PHPStan\Reflection\ResolvedMethodReflection),
Object(PhpParser\Node\Expr\MethodCall), Object(PHPStan\Analyser\MutatingScope))
#2 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1402): PHPStan\Analyser\MutatingScope->methodCallReturnType(Object(PHPStan\Type\UnionType), 'toArray', Object(PhpParser\Node\Expr\MethodCall))
#3 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1408): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()                  
#4 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(557): PHPStan\Analyser\MutatingScope->resolveType(Object(PhpParser\Node\Expr\MethodCall))
#5 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(778): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\MethodCall))
#6 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(557): PHPStan\Analyser\MutatingScope->resolveType(Object(PhpParser\Node\Expr\Assign))
#7 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1437): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\Assign))
#8 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(554): PHPStan\Analyser\NodeScopeResolver->findEarlyTerminatingExpr(Object(PhpParser\Node\Expr\Assign), Object(PHPStan\Analyser\MutatingScope))
#9 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(357): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Expression), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#10 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(518): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\ClassMethod), Array, Object(PHPStan\Analyser\MutatingScope),
Object(Closure))
#11 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(357): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod), Object(PHPStan\Analyser\MutatingScope),
Object(PHPStan\Node\ClassStatementsGatherer))
#12 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(596): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Class_), Array, Object(PHPStan\Analyser\MutatingScope),
Object(PHPStan\Node\ClassStatementsGatherer))
#13 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(357): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#14 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(568): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_), Array, Object(PHPStan\Analyser\MutatingScope),
Object(Closure))
#15 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(327): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Namespace_), Object(PHPStan\Analyser\MutatingScope),
Object(Closure))
#16 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(175): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#17 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(147): PHPStan\Analyser\FileAnalyser->analyseFile('/var/www/html/a...', Array, Object(PHPStan\Rules\LazyRegistry), Object(PHPStan\Collectors\Registry), NULL)
#18 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97): PHPStan\Command\WorkerCommand->PHPStan\Command\{closure}(Array)
#19 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/vendor/clue/ndjson-react/src/Decoder.php(110): _PHPStan_582a9cb8b\Evenement\EventEmitter->emit('data', Array)
#20 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97): _PHPStan_582a9cb8b\Clue\React\NDJson\Decoder->handleData(Array)
#21 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/Util.php(62): _PHPStan_582a9cb8b\Evenement\EventEmitter->emit('data', Array)
#22 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97): _PHPStan_582a9cb8b\React\Stream\Util::_PHPStan_582a9cb8b\React\Stream\{closure}('{"action":"anal...')
#23 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/DuplexResourceStream.php(154): _PHPStan_582a9cb8b\Evenement\EventEmitter->emit('data', Array)
#24 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(201): _PHPStan_582a9cb8b\React\Stream\DuplexResourceStream->handleData(Resource id #9849)
#25 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(173): _PHPStan_582a9cb8b\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
#26 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(107): _PHPStan_582a9cb8b\React\EventLoop\StreamSelectLoop->run()
#27 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\WorkerCommand->execute(Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Input\ArgvInput),
Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Output\ConsoleOutput))
#28 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(868): _PHPStan_582a9cb8b\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Input\ArgvInput),
Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Output\ConsoleOutput))
#29 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(259): _PHPStan_582a9cb8b\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\WorkerCommand),
Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Output\ConsoleOutput))
#30 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157): _PHPStan_582a9cb8b\Symfony\Component\Console\Application->doRun(Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Input\ArgvInput),
Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Output\ConsoleOutput))
#31 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(124): _PHPStan_582a9cb8b\Symfony\Component\Console\Application->run()
#32 phar:///var/www/html/app/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(125): _PHPStan_582a9cb8b\{closure}()
#33 /var/www/html/app/vendor/phpstan/phpstan/phpstan(8): require('phar:///var/www...')
#34 /var/www/html/app/vendor/bin/phpstan(120): include('/var/www/html/a...')
#35 {main}
Child process error (exit code 1):
```

### PHPStan Config
```
parameters:
    inferPrivatePropertyTypeFromConstructor: true
    level: 8
    paths:
        - packages
        - public/typo3conf

includes:
    - vendor/saschaegerer/phpstan-typo3/extension.neon
    - vendor/ssch/typo3-rector/utils/phpstan/config/extension.neon
```

Best regards
Marc

**Comment by sascha-egerer** [comment]
Hi @TWT-MW, this may be solved in master. Could you please test it?

**Comment by TWT-MW** [comment]
Hey @sascha-egerer, it's working with the master-branch.

**Comment by sascha-egerer** [comment]
@TWT-MW I've release 1.8.2 containing the fix.
